### ISSUE TITLE
Use `sample_category` instead of `specimen_type`

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/python-sdk#16]
A grep -R reveals many uses of the specimen_type field in the HuBMAP SDK, convert these uses to use sample_category instead as specimen_type` is deprecated and will go away.

**Comment by yuanzhou** [comment]
@shirey I can't find neither `specimen_type` nor `sample_category` in this repository code.

**Comment by shirey** [comment]
@yuanzhou closing because the SDK will automatically pick up attribute names from Neo4j without having them registered in a schema.
