### ISSUE TITLE
Add new endpoints from entity-api for prov info support used by metadata

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/python-sdk#22]
As a result of https://github.com/hubmapconsortium/entity-api/issues/604, and the fact that ingest-api calls this SDK to make the calls against the new endpoints in entity-api, we'll need to add them to the SDK and publish a new PyPI package.

**Comment by ChuckKollar** [comment]
PR: https://github.com/hubmapconsortium/python-sdk/pull/23
